# Site Settings
title: Sical demonstrators
email:
description: Platform for demos of th SICAL team
baseurl: "/jekflix-template" # the subpath of your site, e.g. /blog
url: "https://sical.github.io/demos-sical" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Sical demonstrators
user_description: No description available.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

collections:
  demonstrations:
      output: true
      permalink: /:collection/:name/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
include: ["_demonstrations"]
exclude: ['package.json', 'src', 'node_modules']
