# Site Settings
title: Sical demonstrators
email:
description: Platform for demos of th SICAL team
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sical.github.io/demos-sical/" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Sical demonstrators
user_description: Platform for demos of th SICAL team.
#disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
#github_username: github_username
#facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username

collections:
  demonstrations:
      output: true
      permalink: /demos-sical/:collection/:name/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
